Repository 2025-Advanced-Capstone-Chaeum/BE, pull requests merged in 2025-05, with the labels that each got.

#99 feat: 쿠키에 토큰 추가 완료
  src/main/java/com/chaeum/api/global/handler/CustomOAuth2LoginHandler.java
Labels: ✨ Feature

#95 feat: 회원별 미션 기능 구현 완료
  src/main/java/com/chaeum/api/domain/attendance/service/AttendanceService.java
  src/main/java/com/chaeum/api/domain/cat/service/CatService.java
  src/main/java/com/chaeum/api/domain/donation/service/DonationService.java
  src/main/java/com/chaeum/api/domain/inventory/service/InventoryService.java
  src/main/java/com/chaeum/api/domain/member/entity/Member.java
  src/main/java/com/chaeum/api/domain/memberMission/controller/MemberMissionController.java
  src/main/java/com/chaeum/api/domain/memberMission/dto/response/MemberMissionResponse.java
  src/main/java/com/chaeum/api/domain/memberMission/entity/MemberMission.java
  src/main/java/com/chaeum/api/domain/memberMission/entity/MissionStatus.java
  src/main/java/com/chaeum/api/domain/memberMission/repository/MemberMissionRepository.java
  src/main/java/com/chaeum/api/domain/memberMission/service/MemberMissionRandomService.java
  src/main/java/com/chaeum/api/domain/memberMission/service/MemberMissionService.java
  src/main/java/com/chaeum/api/domain/mission/controller/MissionController.java
  src/main/java/com/chaeum/api/domain/mission/dto/request/MissionCreateRequest.java
  src/main/java/com/chaeum/api/domain/mission/dto/request/MissionUpdateRequest.java
  src/main/java/com/chaeum/api/domain/mission/entity/MissionType.java
  src/main/java/com/chaeum/api/domain/mission/service/MissionService.java
  src/main/java/com/chaeum/api/domain/missionProgress/controller/MissionProgressController.java
  src/main/java/com/chaeum/api/domain/missionProgress/dto/.gitkeep
  src/main/java/com/chaeum/api/domain/missionProgress/repository/MissionProgressRepository.java
  src/main/java/com/chaeum/api/domain/missionProgress/service/MissionProgressService.java
  src/main/java/com/chaeum/api/global/utils/MemberMissionConstants.java
Labels: ✨ Feature

#102 feat: 수혜자 등록 기능 구현 완료
  src/main/java/com/chaeum/api/domain/member/controller/MemberController.java
  src/main/java/com/chaeum/api/domain/member/dto/request/RegisterBeneficiaryRequest.java
  src/main/java/com/chaeum/api/domain/member/entity/Member.java
  src/main/java/com/chaeum/api/domain/member/event/BeneficiaryEvent.java
  src/main/java/com/chaeum/api/domain/member/service/MemberService.java
  src/main/java/com/chaeum/api/domain/notification/event/NotificationEventListner.java
  src/main/java/com/chaeum/api/global/config/SecurityConfig.java
  src/main/java/com/chaeum/api/global/filter/InternalApiKeyFilter.java
  src/main/java/com/chaeum/api/global/filter/JwtFilter.java
  src/main/java/com/chaeum/api/global/handler/CustomOAuth2LoginHandler.java
  src/main/resources/application.yml.template
Labels: ✨ Feature

#103 refactor: 이미지 업로드 기능 리팩토링
  src/main/java/com/chaeum/api/domain/donation/dto/response/DonationSummaryResponse.java
  src/main/java/com/chaeum/api/domain/donation/event/DonationEvent.java
  src/main/java/com/chaeum/api/domain/funding/controller/FundingController.java
  src/main/java/com/chaeum/api/domain/funding/dto/request/FundingCreateRequest.java
  src/main/java/com/chaeum/api/domain/funding/dto/request/FundingUpdateRequest.java
  src/main/java/com/chaeum/api/domain/funding/dto/response/FundingResponse.java
  src/main/java/com/chaeum/api/domain/funding/dto/response/FundingSummaryResponse.java
  src/main/java/com/chaeum/api/domain/funding/entity/Funding.java
  src/main/java/com/chaeum/api/domain/funding/event/FundingEvent.java
  src/main/java/com/chaeum/api/domain/funding/service/FundingService.java
  src/main/java/com/chaeum/api/domain/review/event/ReviewEvent.java
  src/main/resources/data/04-funding.sql
  src/main/resources/data/12-uploaded_file.sql
Labels: ♻️ Refactor

#106 feat: 프로필 사진 업로드 API 추가 완료
  src/main/java/com/chaeum/api/global/file/controller/FileController.java
Labels: ✨ Feature

#108 refactor: Mock 테스트 데이터 정합성 보완
  src/main/java/com/chaeum/api/domain/paymentRecord/entity/PaymentRecord.java
  src/main/resources/data/01-member.sql
  src/main/resources/data/02-item.sql
  src/main/resources/data/03-inventory.sql
  src/main/resources/data/04-funding.sql
  src/main/resources/data/05-donation.sql
  src/main/resources/data/06-mission.sql
  src/main/resources/data/07-member-mission.sql
  src/main/resources/data/08-cat.sql
  src/main/resources/data/09-attendance.sql
  src/main/resources/data/10-friendship.sql
  src/main/resources/data/11-review.sql
  src/main/resources/data/12-uploaded_file.sql
  src/main/resources/data/13-title.sql
  src/main/resources/data/14-notification.sql
  src/main/resources/data/15-payment-record.sql
Labels: ♻️ Refactor, ✅ Test

#114 refactor: 결제 로직 최적화
  src/main/java/com/chaeum/api/domain/donation/service/DonationService.java
  src/main/java/com/chaeum/api/domain/member/service/MemberService.java
  src/main/java/com/chaeum/api/domain/paymentRecord/dto/request/PaymentCreateRequest.java
  src/main/java/com/chaeum/api/domain/paymentRecord/dto/request/PaymentGatewayInfoRequest.java
  src/main/java/com/chaeum/api/domain/paymentRecord/entity/PaymentGatewayInfo.java
  src/main/java/com/chaeum/api/domain/paymentRecord/entity/PaymentRecord.java
  src/main/java/com/chaeum/api/domain/paymentRecord/service/PaymentRecordService.java
Labels: ♻️ Refactor

#116 refactor: 결제 예외 처리 로직 개선 및 Mock 데이터 보완
  src/main/java/com/chaeum/api/domain/donation/service/DonationService.java
  src/main/java/com/chaeum/api/domain/paymentRecord/controller/PaymentRecordController.java
  src/main/java/com/chaeum/api/domain/paymentRecord/dto/request/PaymentCreateRequest.java
  src/main/java/com/chaeum/api/domain/paymentRecord/entity/PaymentRecord.java
  src/main/java/com/chaeum/api/domain/paymentRecord/service/PaymentRecordService.java
  src/main/resources/data/15-payment-record.sql
Labels: ♻️ Refactor

#118 refactor: 펀딩을 생성한 회원의 id 필드 추가
  src/main/java/com/chaeum/api/domain/funding/dto/response/FundingResponse.java
Labels: ♻️ Refactor
